=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/template.dtd
<!-- ==========================================================================
 This is the DTD for phpLDAPAdmin Templates (draft).

 Copyright (c) 2005 <adezorzi AT rhx DOT it>

 temporary URI for the DTD: http://www.phamm.org/DTD/pla-template-strict.dtd
 Validate your templates here: http://www.stg.brown.edu/service/xmlvalid/
========================================================================== -->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (title,regexp?,icon?,description?,askcontainer?,rdn?,
			visible?,invalid?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (array?, default?, cols?, description?, display?, helper?, hidden?, hint?,
			icon?, onchange*, order?, override?, page?, post?,
			presubmit?, rows?, spacer*, type?, value*, verify?)>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,hint?,id?,location?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT visible (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT array (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sambaMachine.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Machine</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/server.png</icon>
<description>New Samba3 Machine</description>
<askcontainer>1</askcontainer>
<rdn>uid</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
<objectClass id="account"></objectClass>
</objectClasses>

<attributes>
<attribute id="uid">
	<display>Machine Name</display>
	<hint>The machine name should end with a $</hint>
        <icon>images/terminal.png</icon>
	<onchange>autoFill:cn,%uid%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
        <display>UID Number</display>
        <hint>Automatically determined</hint>
        <order>2</order>
        <page>1</page>
        <presubmit>=php.GetNextNumber(/,uid)</presubmit>
</attribute>
<attribute id="gidNumber">
        <display>GID Number</display>
        <order>3</order>
        <page>1</page>
        <value>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</value>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<location>side</location>
		<value></value>
	</helper>
	<order>2</order>
	<page>1</page>
        <post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
        <value>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</value>
</attribute>
<attribute id="sambaAcctFlags">
	<hidden>1</hidden>
	<value>[W]</value>
</attribute>
<attribute id="homeDirectory">
	<hidden>1</hidden>
	<value>/dev/null</value>
</attribute>
<attribute id="cn">
	<hidden>1</hidden>
	<value></value>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sendmailMTAClass.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Sendmail Domain</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Domain</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTACluster</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAClass"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>images/object.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAClassValue">
	<display>Email domain</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAClassName">
	<default>w</default>
	<hidden>1</hidden>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/ou.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Organisational Unit</title>
<!-- <regexp>^o=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>New Organisational Unit</description>
<askcontainer>1</askcontainer>
<rdn>ou</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="organizationalUnit"></objectClass>
</objectClasses>

<attributes>
<attribute id="ou">
	<description>Organisational Unit</description>
	<display>Organisational Unit</display>
	<hint>don't include "ou="</hint>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/organizationalRole.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Organisational Role</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/o.png</icon>
<description>New Organisational Role</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="organizationalRole"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Role CN</display>
	<order>1</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>images/phone.png</icon>
	<order>2</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>3</order>
	<spacer>1</spacer>
</attribute>

<attribute id="description">
	<display>Comments</display>
	<icon>images/light.png</icon>
	<order>4</order>
	<spacer>1</spacer>
</attribute>

<attribute id="roleOccupant">
	<display>Occupant</display>
	<icon>images/object.png</icon>
	<order>5</order>
	<spacer>1</spacer>
</attribute>

<attribute id="street">
	<display>Street Address</display>
	<icon>images/mail.png</icon>
	<order>6</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>7</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>8</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>9</order>
	<spacer>1</spacer>
</attribute>

<attribute id="postalAddress">
	<display>Postal Address</display>
	<icon>images/mail.png</icon>
	<order>10</order>
	<spacer>1</spacer>
</attribute>
<attribute id="registeredAddress">
	<display>Registered Address</display>
	<icon>images/mail.png</icon>
	<order>11</order>
</attribute>

</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/courierMailAlias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Courier Mail Alias</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail_alias.png</icon>
<description>New Courier Mail Alias</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>
<invalid>0</invalid>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="courierMailAlias"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Common Name</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="maildrop">
	<display>Maildrop</display>
	<order>4</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/posixAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>User Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New User Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>4</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<icon>images/terminal.png</icon>
	<order>6</order>
	<page>1</page>
	<presubmit>=php.GetNextNumber(/,uid)</presubmit>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>7</order>
	<page>1</page>
	<value>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</value>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<order>9</order>
	<page>1</page>
	<value>=php.PickList(/,(objectClass=posixAccount),loginShell,%loginShell%)</value>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<helper>
		<default>md5</default>
		<display>Encryption</display>
		<id>enc</id>
		<location>side</location>
		<value>blowfish</value>
		<value>clear</value>
		<value>crypt</value>
		<value>ext_des</value>
		<value>md5</value>
		<value>md5crypt</value>
		<value>sha</value>
		<value>smd5</value>
		<value>ssha</value>
	</helper>
	<icon>images/lock.png</icon>
	<order>5</order>
	<page>1</page>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<spacer>1</spacer>
	<type>password</type>
	<verify>1</verify>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/kolabPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Kolab User Entry</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Address Book Entry</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>
<invalid>1</invalid>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>4</order>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<helper>
		<default>md5</default>
		<display>Encryption</display>
		<id>enc</id>
		<location>side</location>
		<value>blowfish</value>
		<value>clear</value>
		<value>crypt</value>
		<value>ext_des</value>
		<value>md5</value>
		<value>md5crypt</value>
		<value>sha</value>
		<value>smd5</value>
		<value>ssha</value>
	</helper>
	<icon>images/lock.png</icon>
	<order>5</order>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<spacer>1</spacer>
	<type>password</type>
	<verify>1</verify>
</attribute>

<attribute id="title">
	<display>Title</display>
	<icon>images/ou.png</icon>
	<order>6</order>
</attribute>
<attribute id="alias">
	<display>Alias</display>
	<order>7</order>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>8</order>
</attribute>
<attribute id="ou">
	<display>Organisational unit</display>
	<order>9</order>
</attribute>
<attribute id="roomNumber">
	<display>Room Number</display>
	<order>10</order>
	<spacer>1</spacer>
</attribute>

<attribute id="street">
	<display>Address</display>
	<icon>images/mail.png</icon>
	<order>11</order>
</attribute>
<attribute id="postOfficeBox">
	<display>Post box</display>
	<order>12</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>13</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>14</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>15</order>
</attribute>
<attribute id="c">
	<display>Country</display>
	<order>16</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>images/phone.png</icon>
	<order>17</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>18</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>19</order>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/inetOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Address Book Entry</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Address Book Entry</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="street">
	<cols>50</cols>
	<display>Street</display>
	<icon>images/mail.png</icon>
	<order>4</order>
	<page>1</page>
	<rows>4</rows>
	<type>textarea</type>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>5</order>
	<page>1</page>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>6</order>
	<page>1</page>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>7</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>images/phone.png</icon>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>9</order>
	<page>1</page>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>9</order>
	<page>1</page>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>10</order>
	<page>1</page>
</attribute>
</attributes>
</template>
