=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/template.dtd
<!-- ==========================================================================
 This is the DTD for phpLDAPAdmin Templates (draft).

 Copyright (c) 2005 <adezorzi AT rhx DOT it>

 temporary URI for the DTD: http://www.phamm.org/DTD/pla-template-strict.dtd
 Validate your templates here: http://www.stg.brown.edu/service/xmlvalid/
========================================================================== -->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (title,regexp?,icon?,description?,askcontainer?,rdn?,
			visible?,invalid?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (array?, default?, cols?, description?, display?, helper?, hidden?, hint?,
			icon?, onchange*, order?, override?, page?, post?,
			presubmit?, rows?, spacer*, type?, value*, verify?)>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,hint?,id?,location?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT visible (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT array (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/mozillaOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Address Book Entry (mozillaOrgPerson)</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Address Book Entry</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="mozillaAddressBookEntry"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First Name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%sn% %givenName%</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last Name</display>
	<onchange>autoFill:cn,%sn% %givenName%</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
</attribute>
<attribute id="mozillaNickName">
	<display>Nickname</display>
	<order>4</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mail">
	<display>t_email</display>
	<order>5</order>
</attribute>
<attribute id="mozillaSecondEmail">
	<display>Additional email</display>
	<order>6</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work Phone</display>
	<icon>images/phone.png</icon>
	<order>7</order>
</attribute>
<attribute id="homePhone">
	<display>Home Phone</display>
	<order>8</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>9</order>
</attribute>
<attribute id="pager">
	<display>Page</display>
	<order>10</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>11</order>
	<spacer>1</spacer>
</attribute>
<attribute id="homePostalAddress">
	<display>Home Address</display>
	<order>12</order>
</attribute>
<attribute id="mozillaHomePostalAddress2">
	<display>Home Address 2</display>
	<order>13</order>
</attribute>
<attribute id="mozillaHomeLocalityName">
	<display>Home City</display>
	<order>14</order>
</attribute>
<attribute id="mozillaHomeState">
	<display>Home State</display>
	<order>15</order>
</attribute>
<attribute id="mozillaHomePostalCode">
	<display>Home ZIP/Postal Code</display>
	<order>16</order>
</attribute>
<attribute id="mozillaHomeCountryName">
	<display>Home Country</display>
	<order>17</order>
</attribute>
<attribute id="mozillaHomeUrl">
	<display>Home Web page</display>
	<order>18</order>
	<spacer>1</spacer>
</attribute>
<attribute id="title">
	<display>Work Title</display>
	<order>19</order>
</attribute>
<attribute id="ou">
	<display>Work Department</display>
	<order>20</order>
</attribute>
<attribute id="o">
	<display>Work Organization</display>
	<order>21</order>
</attribute>
<attribute id="street">
	<display>Work Address</display>
	<order>22</order>
</attribute>
<attribute id="mozillaWorkStreet2">
	<display>Work Address 2</display>
	<order>23</order>
</attribute>
<attribute id="l">
	<display>Work City</display>
	<order>24</order>
</attribute>
<attribute id="st">
	<display>Work State/Province</display>
	<order>25</order>
</attribute>
<attribute id="postalCode">
	<display>Work ZIP/Postal Code</display>
	<order>26</order>
</attribute>
<attribute id="c">
	<display>Work Country</display>
	<order>27</order>
</attribute>
<attribute id="mozillaWorkUrl">
	<display>Work Web page</display>
	<order>28</order>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/alias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<!--This template doesnt work needs modification to the Engine.-->
<template>
<title>LDAP Alias</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail_alias.png</icon>
<description>New LDAP Alias</description>
<askcontainer>1</askcontainer>
<rdn>aliasedObjectName</rdn>
<visible>1</visible>
<invalid>1</invalid>

<objectClasses>
<objectClass id="alias"></objectClass>
<objectClass id="extensibleObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="aliasedObjectName">
	<display>Alias To</display>
	<helper>
		<display></display>
		<location>side</location>
		<value>=php.DrawChooserLink(aliasedObjectName,0)</value>
	</helper>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/dNSDomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>DNS Entry</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/dc.png</icon>
<description>New DNS Entry</description>
<askcontainer>1</askcontainer>
<rdn>dc</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="dnsDomain"></objectClass>
<objectClass id="domainRelatedObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="domainComponent">
	<description>Domain Component</description>
	<display>DC Name</display>
	<order>1</order>
	<override>dc</override>
	<page>1</page>
</attribute>
<attribute id="associatedDomain">
	<display>Associated Domain</display>
	<order>2</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/simpleSecurityObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Simple Security Object</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Simple Security Object</description>
<askcontainer>1</askcontainer>
<rdn>userid</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="account"></objectClass>
<objectClass id="simpleSecurityObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="userid">
	<display>User Name</display>
	<icon>images/uid.png</icon>
	<order>1</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<helper>
		<default>md5</default>
		<display>Encryption</display>
		<id>enc</id>
		<location>side</location>
		<value>blowfish</value>
		<value>clear</value>
		<value>crypt</value>
		<value>ext_des</value>
		<value>md5</value>
		<value>md5crypt</value>
		<value>sha</value>
		<value>smd5</value>
		<value>ssha</value>
	</helper>
	<icon>images/lock.png</icon>
	<order>5</order>
	<page>1</page>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<type>password</type>
	<verify>1</verify>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sendmailMTACluster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Sendmail Cluster</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Cluster</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTACluster</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTA"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Alias To</display>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sambaSamAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Samba3 Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>4</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<order>5</order>
	<page>1</page>
	<presubmit>=php.GetNextNumber(/,uid)</presubmit>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<location>side</location>
		<value></value>
	</helper>
	<order>6</order>
	<page>1</page>
	<post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<spacer>1</spacer>
	<value>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</value>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<helper>
		<default>md5</default>
		<display>Encryption</display>
		<id>enc</id>
		<location>side</location>
		<value>blowfish</value>
		<value>clear</value>
		<value>crypt</value>
		<value>ext_des</value>
		<value>md5</value>
		<value>md5crypt</value>
		<value>sha</value>
		<value>smd5</value>
		<value>ssha</value>
	</helper>
	<icon>images/lock.png</icon>
	<onchange>autoFill:sambaLMPassword,%userPassword%</onchange>
	<onchange>autoFill:sambaNTPassword,%userPassword%</onchange>
	<order>7</order>
	<page>1</page>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<type>password</type>
	<verify>1</verify>
</attribute>
<attribute id="sambaLMPassword">
	<display>LM Password</display>
	<order>8</order>
	<page>1</page>
	<post>=php.SambaPassword(LM,%sambaLMPassword%)</post>
	<type>password</type>
</attribute>
<attribute id="sambaNTPassword">
	<display>NT Password</display>
	<order>9</order>
	<page>1</page>
	<post>=php.SambaPassword(NT,%sambaNTPassword%)</post>
	<spacer>1</spacer>
	<type>password</type>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<icon>images/terminal.png</icon>
	<order>10</order>
	<page>1</page>
	<value>=php.PickList(/,(objectClass=posixAccount),loginShell,%loginShell%)</value>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>11</order>
	<page>1</page>
	<value>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</value>
</attribute>
<attribute id="sambaPrimaryGroupSID">
	<display>Primary Group ID</display>
	<helper>
		<id>sidpgsuffix</id>
		<location>side</location>
		<value></value>
	</helper>
	<order>13</order>
	<page>1</page>
	<post>=php.Join(-,(%sambaPrimaryGroupSID%,%sidpgsuffix%))</post>
	<spacer>1</spacer>
	<value>=php.PickList(/,(objectClass=sambaGroupMapping),sambaSID,%sambaSID% (%cn%),sambaPrimaryGroupSID)</value>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<order>14</order>
	<page>1</page>
</attribute>
<attribute id="sambaAcctFlags">
	<hidden>1</hidden>
	<value>[U]</value>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sambaGroupMapping.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Group Mapping</title>
<!-- <regexp>^ou=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>New Samba3 Group Mapping</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
<objectClass id="sambaGroupMapping"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="displayName">
	<display>Windows Name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<hint>Automatically determined</hint>
	<order>3</order>
	<page>1</page>
	<presubmit>=php.GetNextNumber(/,gid)</presubmit>
	<spacer>1</spacer>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<location>side</location>
		<value></value>
	</helper>
	<order>4</order>
	<page>1</page>
	<post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<value>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</value>
</attribute>
<attribute id="sambaGroupType">
	<default>2</default>
	<display>Samba Group Type</display>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
	<value id="2">Domain Group</value>
	<value id="4">Local Group</value>
	<value id="5">Well-known Group</value>
</attribute>
<attribute id="memberUid">
	<array>10</array>
	<display>Users</display>
	<helper>
		<location>side</location>
<!--		<value>=php.DrawChooserLink(memberUid,0)</value> -->
	</helper>
	<hidden>0</hidden>
	<order>10</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/courierMailAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Courier Mail Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail_account.png</icon>
<description>New Courier Mail Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>
<invalid>0</invalid>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="courierMailAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="uid">
	<display>User ID</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:homeDirectory,/home/users/%uid%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="mail">
        <display>Email</display>
	<icon>images/mail.png</icon>
        <order>2</order>
        <page>1</page>
</attribute>
<attribute id="mailbox">
	<display>Mailbox</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
	<spacer>1</spacer>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>5</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<icon>images/terminal.png</icon>
	<order>6</order>
	<page>1</page>
	<presubmit>=php.GetNextNumber(/,uid)</presubmit>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>7</order>
	<page>1</page>
	<value>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</value>
</attribute>
<attribute id="homeDirectory">
	<display>Home Directory</display>
	<order>8</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<helper>
		<default>md5</default>
		<display>Encryption</display>
		<id>enc</id>
		<location>side</location>
		<value>blowfish</value>
		<value>clear</value>
		<value>crypt</value>
		<value>ext_des</value>
		<value>md5</value>
		<value>md5crypt</value>
		<value>sha</value>
		<value>smd5</value>
		<value>ssha</value>
	</helper>
	<icon>images/lock.png</icon>
	<order>9</order>
	<page>1</page>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<type>password</type>
	<verify>1</verify>
</attribute>
</attributes>
</template>
