=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/template.dtd
<!-- ==========================================================================
 This is the DTD for phpLDAPAdmin Templates (draft).

 Copyright (c) 2005 <adezorzi AT rhx DOT it>

 temporary URI for the DTD: http://www.phamm.org/DTD/pla-template-strict.dtd
 Validate your templates here: http://www.stg.brown.edu/service/xmlvalid/
========================================================================== -->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (title,regexp?,icon?,description?,askcontainer?,rdn?,
			visible?,invalid?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (array?, default?, cols?, description?, display?, helper?, hidden?, hint?,
			icon?, onchange*, order?, override?, page?, post?,
			presubmit?, rows?, spacer*, type?, value*, verify?)>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,hint?,id?,location?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT visible (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT array (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sendmailVirtualUser.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Sendmail Virtual Users</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Virtual User</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTAMapObject</rdn>
<visible>1</visible>
<invalid>1</invalid>

<objectClasses>
<objectClass id="sendmailMTAMapObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>images/object.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Email alias</display>
	<hint>use @example.com to map entire domain</hint>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAMapValue">
	<display>Recipient Addresses</display>
	<hint>use %1 to map user name port of address</hint>
	<order>4</order>
	<page>1</page>
	<type>textarea</type>
</attribute>
<attribute id="sendmailMTAMapName">
	<hidden>1</hidden>
	<value>virtuser</value>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Example entry</title>
<regexp>^$</regexp>
<icon>images/star.png</icon>
<description>This is the description</description>
<rdn>o</rdn>
<visible>0</visible>

<objectClasses>
<objectClass id="organization"></objectClass>
</objectClasses>

<attributes>
<attribute id="attribute1">
	<description>This is the attribute description</description>
	<display>Attribute 1</display>
	<hint>This is an example</hint>
	<icon>images/user.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="attribute2">
	<description>This is the attribute description</description>
	<display>Attribute 2</display>
	<order>2</order>
	<page>2</page>
</attribute>
<attribute id="attribute3">
	<description>This is the attribute description</description>
	<display>Attribute 3</display>
	<order>1</order>
	<page>2</page>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sambaDomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba Domain</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/dc.png</icon>
<description>New Samba Domain</description>
<askcontainer>1</askcontainer>
<rdn>sambaDomainName</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sambaDomain"></objectClass>
</objectClasses>

<attributes>
<attribute id="sambaDomainName">
	<display>Samba Domain Name</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<hint>Samba SID is in the format S-1-5-21-x-y-z</hint>
	<order>2</order>
	<page>1</page>
	<value>S-1-5-21-</value>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sendmailMTAMapObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<!--This template doesnt work needs modification to the Engine.-->
<template>
<title>Sendmail Relays</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Relays</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTACluster</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAClass"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>images/object.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Host/Network/Address</display>
	<order>3</order>
	<page>1</page>
	<value>RELAY: Allow host/network/address to relay</value>
	<value>OK: Accept local mail but disallow relay</value>
	<value>REJECT: Reject messages</value>
	<value>DISCARD: Discard messages</value>
	<value>SKIP: Apply default action to messages</value>
	<value>ERROR: Reject message with custom error</value>
</attribute>
<attribute id="sendmailMTAMapName">
	<hidden>1</hidden>
	<value>access</value>
</attribute>
</attributes>
</template>

=== FH-Complete/FHC-Core/admin/phpldapadmin/templates/sendmailMTAAliasObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Sendmail Alias</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Alias</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTACluster</rdn>
<visible>1</visible>
<invalid>1</invalid>

<objectClasses>
<objectClass id="sendmailMTAAliasObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>images/object.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Email alias</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAAliasValue">
	<display>Recipient Addresses</display>
	<order>4</order>
	<page>1</page>
	<type>textarea</type>
</attribute>
<attribute id="sendmailMTAAliasGrouping">
	<default>aliases</default>
	<hidden>1</hidden>
</attribute>
</attributes>
</template>
